name: Unit Of Work Nuget Package Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
  
  deploy:    
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}
          nuget-version: '5.x'
      - name: Pack nuget Package
        run: dotnet pack --configuration Release
      - name: Push Package To Myget
        run: nuget push **/*.nupkg ${{ secrets.NUGET_DEPLOY_KEY }} -s https://www.myget.org/F/my/api/v3/index.json
        # run: dotnet nuget push **/*.nupkg --skip-duplicate --no-symbols true -s https://www.myget.org/F/my/api/v3/index.json --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
          
