name: Unit Of Work Nuget Package Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
  
  deploy:    
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack nuget Package
        run: dotnet pack --configuration Release
      - name: push package to myget
        run: dotnet nuget push **/*.nupkg --api-key ${{ NUGET_DEPLOY_KEY }} --source https://www.myget.org/F/my/api/v3/index.json
